databases:
  - name: fukusyu-db
    plan: free

services:
  - type: web
    name: fukusyu
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python3 -m flask shell <<< 'from app import db; db.create_all()'"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fukusyu-db
          property: connectionString # ← ここを修正しました
