services:
  # --------------------
  # Webアプリの設定
  # --------------------
  - type: web
    name: fukusyu    # ここは好きな名前に変更できます
    env: python
    plan: free                # 無料プラン
    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "python3 -m flask shell <<< 'from app import db; db.create_all()'"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11           # 安定しているPythonのバージョンを指定
      - key: SECRET_KEY
        generateValue: true   # Renderが自動で安全なキーを生成してくれる
      - key: DATABASE_URL
        fromDatabase:
          name: fukusyu-db # Renderで作成したDBの名前に合わせる
          property: internalConnectionString

  # --------------------
  # データベースの設定
  # --------------------
  - type: psql
    name: fukusyu-db     # ここは好きな名前に変更できます
    plan: free                # 無料プラン
